version: "3.3"

services:

#-----------------------------------------------------------------
  # CHECKOUT
  rfid-production-checkout-1:
    container_name: rfid-production-checkout-1
    image: ghcr.io/bookwaves/checkout-web:2.0.3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-checkout-1.rule=PathPrefix(`/production/checkout/1/`)"
      #- "traefik.http.routers.rfid-production-checkout-1.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-1.stripprefix.prefixes=/production/checkout/1/"
      - "traefik.http.routers.rfid-production-checkout-1.middlewares=rfid-production-checkout-1"
      - "traefik.http.services.rfid-production-checkout-1.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - internal
      - traefik

  rfid-production-checkout-service-1:
    container_name: rfid-production-checkout-service-1
    image: ghcr.io/bookwaves/checkout-service:1.2.7-demo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      PAIA_URL: "http://www.example.org/paia"
      TOTP_URL: "http://www.example.org/qr"
      TOTP_KEY: "12345changeme"
      ALMA_API_KEY: "ADD-THE-ALMA-API-KEY-HERE"
      TERMINAL_ID: 1
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      POSTGRES_HOST: rfid-production-db
      POSTGRES_PORT: 5432
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-checkout-service-1.rule=PathPrefix(`/production/checkout/1/api`)"
      #- "traefik.http.routers.rfid-production-checkout-service-1.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-service-1.stripprefix.prefixes=/production/checkout/1/api"
      - "traefik.http.routers.rfid-production-checkout-service-1.middlewares=rfid-production-checkout-service-1"
      - "traefik.http.services.rfid-production-checkout-service-1.loadbalancer.server.port=9100"
      - "traefik.http.routers.rfid-production-checkout-service-1.service=rfid-production-checkout-service-1"

      # Expose admin panel
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.rule=PathPrefix(`/production/checkout/1/admin`)"
      #- "traefik.http.routers.rfid-production-checkout-service-1-admin.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-service-1-admin.stripprefix.prefixes=/production/checkout/1/admin"
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.middlewares=rfid-production-checkout-service-1-admin"
      - "traefik.http.services.rfid-production-checkout-service-1-admin.loadbalancer.server.port=9101"
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.service=rfid-production-checkout-service-1-admin"
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      - internal
      - traefik

# all the tls lines are commented out, since traefik is not configured for ssl


 #-----------------------------------------------------------------
  # DATABASE
  rfid-production-db:
    container_name: rfid-production-db
    image: postgres:13
    command: postgres -c 'max_connections=200'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      TZ: Europe/Berlin
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 7654:5432
    networks:
      - internal

  adminer-stack:
    container_name: adminer-stack
    image: adminer
    restart: always
    ports:
      - "8998:8080"
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    external: false
