version: "3.3"

services:

#-----------------------------------------------------------------
  # CHECKOUT
  rfid-production-checkout-1:
    container_name: rfid-production-checkout-1
    image: ghcr.io/bookwaves/checkout-web:2.0.3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-checkout-1.rule=PathPrefix(`/production/checkout/1/`)"
      #- "traefik.http.routers.rfid-production-checkout-1.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-1.stripprefix.prefixes=/production/checkout/1/"
      - "traefik.http.routers.rfid-production-checkout-1.middlewares=rfid-production-checkout-1"
      - "traefik.http.services.rfid-production-checkout-1.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - internal
      - traefik

  rfid-production-checkout-service-1:
    container_name: rfid-production-checkout-service-1
    image: ghcr.io/bookwaves/checkout-service:1.2.7-demo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      PAIA_URL: "http://www.example.org/paia"
      TOTP_URL: "http://www.example.org/qr"
      TOTP_KEY: "12345changeme"
      ALMA_API_KEY: "ADD-THE-ALMA-API-KEY-HERE"
      TERMINAL_ID: 1
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      POSTGRES_HOST: rfid-production-db
      POSTGRES_PORT: 5432
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-checkout-service-1.rule=PathPrefix(`/production/checkout/1/api`)"
      #- "traefik.http.routers.rfid-production-checkout-service-1.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-service-1.stripprefix.prefixes=/production/checkout/1/api"
      - "traefik.http.routers.rfid-production-checkout-service-1.middlewares=rfid-production-checkout-service-1"
      - "traefik.http.services.rfid-production-checkout-service-1.loadbalancer.server.port=9100"
      - "traefik.http.routers.rfid-production-checkout-service-1.service=rfid-production-checkout-service-1"

      # Expose admin panel
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.rule=PathPrefix(`/production/checkout/1/admin`)"
      #- "traefik.http.routers.rfid-production-checkout-service-1-admin.tls=true"
      - "traefik.http.middlewares.rfid-production-checkout-service-1-admin.stripprefix.prefixes=/production/checkout/1/admin"
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.middlewares=rfid-production-checkout-service-1-admin"
      - "traefik.http.services.rfid-production-checkout-service-1-admin.loadbalancer.server.port=9101"
      - "traefik.http.routers.rfid-production-checkout-service-1-admin.service=rfid-production-checkout-service-1-admin"
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      - internal
      - traefik

# all the tls lines are commented out, since traefik is not configured for ssl


# GATES
  rfid-production-gate-1:
    container_name: rfid-production-gate-1
    image: ghcr.io/bookwaves/gate-web:1.5.4
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-gate-1.rule=PathPrefix(`/production/gate/1/`)"
      #- "traefik.http.routers.rfid-production-gate-1.tls=true"
      - "traefik.http.middlewares.rfid-production-gate-1.stripprefix.prefixes=/production/gate/1/"
      - "traefik.http.routers.rfid-production-gate-1.middlewares=rfid-production-gate-1"
      - "traefik.http.services.rfid-production-gate-1.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - internal
      - traefik

  rfid-production-gate-service-1:
    container_name: rfid-production-gate-service-1
    image: ghcr.io/bookwaves/gate-service:1.5.5-demo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      GATE_ID: 1
      ALMA_KEY: l8xxxxxxxxxxxxx
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      POSTGRES_HOST: rfid-production-db
      POSTGRES_PORT: 5432
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-gate-service-1.rule=PathPrefix(`/production/gate/1/api`)"
      #- "traefik.http.routers.rfid-production-gate-service-1.tls=true"
      - "traefik.http.middlewares.rfid-production-gate-service-1.stripprefix.prefixes=/production/gate/1/api"
      - "traefik.http.routers.rfid-production-gate-service-1.middlewares=rfid-production-gate-service-1"
      - "traefik.http.services.rfid-production-gate-service-1.loadbalancer.server.port=9190"
      - "traefik.http.routers.rfid-production-gate-service-1.service=rfid-production-gate-service-1"

      # Expose admin panel
      - "traefik.http.routers.rfid-production-gate-service-1-admin.rule=PathPrefix(`/production/gate/1/admin`)"
      #- "traefik.http.routers.rfid-production-gate-service-1-admin.tls=true"
      - "traefik.http.middlewares.rfid-production-gate-service-1-admin.stripprefix.prefixes=/production/gate/1/admin"
      - "traefik.http.routers.rfid-production-gate-service-1-admin.middlewares=rfid-production-gate-service-1-admin"
      - "traefik.http.services.rfid-production-gate-service-1-admin.loadbalancer.server.port=9191"
      - "traefik.http.routers.rfid-production-gate-service-1-admin.service=rfid-production-gate-service-1-admin"
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      - internal
      - traefik



 # ALMA
  rfid-production-alma-service:
    container_name: rfid-production-alma-service
    image: ghcr.io/bookwaves/alma-service:1.3.5-DEMO
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      POSTGRES_HOST: rfid-production-db
      POSTGRES_PORT: 5432
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.alma.rule=PathPrefix(`/alma`, `/production/alma-service`)"
      # Override priority - default priority is based on rule length, that is wrong in this
      # case as the admin rule is more specific and must match first
      - "traefik.http.routers.alma.priority=1"
      - "traefik.http.routers.alma.tls=true"
      - "traefik.http.middlewares.alma-mw.stripprefix.prefixes=/alma,/production/alma-service"
      - "traefik.http.routers.alma.middlewares=alma-mw"
      - "traefik.http.services.alma.loadbalancer.server.port=9100"
      - "traefik.http.routers.alma.service=alma"

      # Expose admin panel
      - "traefik.http.routers.alma-admin.rule=PathPrefix(`/production/alma-service/admin`)"
      # See comment for router alma
      - "traefik.http.routers.alma-admin.priority=2"
      - "traefik.http.routers.alma-admin.tls=true"
      - "traefik.http.middlewares.alma-admin.stripprefix.prefixes=/production/alma-service/admin"
      - "traefik.http.routers.alma-admin.middlewares=alma-admin"
      - "traefik.http.services.alma-admin.loadbalancer.server.port=9101"
      - "traefik.http.routers.alma-admin.service=alma-admin"
    networks:
      - internal
      - traefik
      
# DASHBOARD
  rfid-production-dashboard-service:
    container_name: rfid-production-dashboard-service
    image: ghcr.io/bookwaves/dashboard-service:1.2.1-demo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      POSTGRES_HOST: rfid-production-db
      POSTGRES_PORT: 5432
      PAIA_URL: "https://api.ub.tu-dortmund.de/paia/"
      ALMA_API_KEY: "l8xxxxx"
      HOSTNAMEPREFIX: rfid-production-
      GATEURLTEMPLATE: https://rfid.ub.tu-dortmund.de/production/gate/{id}/
    labels:
      - "traefik.http.routers.rfid-production-dashboard-service.rule=PathPrefix(`/production/dashboard/api`)"
      - "traefik.http.routers.rfid-production-dashboard-service.tls=true"
      - "traefik.http.middlewares.rfid-production-dashboard-service.stripprefix.prefixes=/production/dashboard/api"
      - "traefik.http.routers.rfid-production-dashboard-service.middlewares=rfid-production-dashboard-service"
      - "traefik.http.services.rfid-production-dashboard-service.loadbalancer.server.port=9200"
    networks:
      - internal
      - traefik

  rfid-production-dashboard:
    container_name: rfid-production-dashboard
    image: ghcr.io/bookwaves/dashboard-web:1.2.0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.http.routers.rfid-production-dashboard.rule=PathPrefix(`/production/dashboard/`)"
      - "traefik.http.routers.rfid-production-dashboard.tls=true"
      - "traefik.http.middlewares.rfid-production-dashboard.stripprefix.prefixes=/production/dashboard/"
      - "traefik.http.routers.rfid-production-dashboard.middlewares=rfid-production-dashboard"
      - "traefik.http.services.rfid-production-dashboard.loadbalancer.server.port=80"
    networks:
      - internal
      - traefik
      
 #-----------------------------------------------------------------
  # DATABASE
  rfid-production-db:
    container_name: rfid-production-db
    image: postgres:13
    command: postgres -c 'max_connections=200'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always
    environment:
      POSTGRES_USER: rfiddbuser
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: rfid
      TZ: Europe/Berlin
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - 7654:5432
    networks:
      - internal

  adminer-stack:
    container_name: adminer-stack
    image: adminer
    restart: always
    ports:
      - "8998:8080"
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    external: false
