INSERT INTO public.rfidreader (id, info, type) VALUES (1, 'Simulated Checkout Reader', 'SIMULATION');
INSERT INTO public.rfidreader (id, info, type) VALUES (2, 'Simulated Gate Reader', 'SIMULATION');
INSERT INTO public.rfidreader (id, info, type) VALUES (3, 'Simulated Staff Reader', 'SIMULATION');
INSERT INTO public.rfidreader (id, info, type) VALUES (4, 'Simulated Staff Reader 2', 'SIMULATION');
INSERT INTO public.rfidreaderproperty (rfidreader_id, value, key) VALUES (1, '12345-true,6789-false', 'media-ids');
INSERT INTO public.rfidreaderproperty (rfidreader_id, value, key) VALUES (2, '12345-true,6789-false', 'media-ids');
INSERT INTO public.rfidreaderproperty (rfidreader_id, value, key) VALUES (3, '12345-true', 'media-ids');
INSERT INTO public.rfidreaderproperty (rfidreader_id, value, key) VALUES (4, '6789-false', 'media-ids');
INSERT INTO public.selfserviceterminal (id, circ_desk, enable_borrow, enable_return, enabled, front_camera, infotext, library, login_timeout, name, rfidreader_id) VALUES (1, 'TODO_ADD_ID_FROM_YOUR_ALMA', true, true, true, true, 'Hello BookWaves :-D', 'TODO_ADD_ID_FROM_YOUR_ALMA', 60, 'Demo Selbsverbucher', 1);
INSERT INTO public.gate (id, enabled, infotext, name, rfidreader_id) VALUES (1, true, 'Hello BookWaves :-D', 'Demo Ausgangsgate', 2);
INSERT INTO public.almaservicereader (id, enabled, reader_id) VALUES (1, true, 3);
INSERT INTO public.almaservicereader (id, enabled, reader_id) VALUES (2, true, 4);
INSERT INTO public.almaservicereaderiprange (almaservicereader_id, iprange) VALUES (1, '0.0.0.0/0');
INSERT INTO public.dashboard (id, title) VALUES (1, 'Demo Dashboard');
INSERT INTO public.dashboard_selfserviceterminal (dashboard_id, terminals_id) VALUES (1, 1);
INSERT INTO public.dashboard_gate (dashboard_id, gates_id) VALUES (1, 1);
INSERT INTO public.dashboard_almaservicereader (dashboard_id, almaservicereader_id) VALUES (1, 1);
INSERT INTO public.dashboard_almaservicereader (dashboard_id, almaservicereader_id) VALUES (1, 2);
